application:
  environment:
    php:
      version: 5.5
filter:
  paths:
    - src/*
before_commands:
    - "composer update --prefer-source"
checks:
    php:
        code_rating: true
        duplication: true
