webtaxi_main:
    resource: "@WebtaxiMainBundle/Controller/"
    type:     annotation
    prefix:   /


_webtaxi_map:
    path:     /
    defaults: { _controller: WebtaxiMainBundle:Map:index }


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_confirmed:
    path:     /
    defaults: { _controller: WebtaxiMainBundle:Map:index }

