<?php

namespace Webtaxi\MainBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * UserChangeEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserChangeEntryRepository extends EntityRepository
{
}
